version: '3.8'

services:
    server:
        container_name: proj_celery-server
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        entrypoint: /app/docker/backend/server-entrypoint.sh
        volumes:
            - ./backend/:/app/backend/django_static
        expose:
            - 8001
        env_file:
            - ./backend/.env

    worker:
        container_name: proj_celery-worker
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        env_file:
            - ./backend/.env
        entrypoint: /app/docker/backend/worker-entrypoint.sh
        volumes:
            - ./backend/:/app/backend/django_static
        depends_on:
            - server
            - redis
    redis:
        container_name: proj_celery-redis
        restart: unless-stopped
        image: redis:7.0.5-alpine
        expose:
            - 6379
    db:
        container_name: proj_celery-db
        image: postgres:13.0-alpine
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_DB: ${DJANGO_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        expose:
            - 5432

volumes:
    postgres_data:
